Races:
  Armat:
    Vulnerable-Damage-Multiplier: 1.5
    Sink-Gravity-Value: 0.42
    Damage-Inversion:
      Lower-Bound: 3.0
      Upper-Bound: 30.0
    Damage-Reduction:
      Starting-Point: 8.0
      Damage-Multiplier: 0.8
    Absolute-Damage:
      Amount: 1.0
      Min-Attack-Cooldown: 1.0