Races:
  Armat:
    Vulnerable-Damage-Multiplier: 1.5
    Sink-Gravity-Value: 0.42
    # Leather armor set bonus
    Damage-Inversion:
      Lower-Bound: 3.0
      Upper-Bound: 30.0
    # Copper armor set bonus
    Mining-Bonus:
      Upper-Bound: 3.0
      Step: 0.25
    # Chainmail armor set bonus
    Damage-Dodge:
      Max-Chance: 0.5
      Parry-Damage-Percent: 0.6
      Parry-Armor-Penalty: 1
    # Iron armor set bonus
    Damage-Reduction:
      Starting-Point: 8.0
      Damage-Multiplier: 0.8
    # Golden armor set bonus
    Alchemy:
      Effect-Duration-Multiplier: 1.25
    # Diamond armor set bonus
    Absolute-Damage:
      Amount: 1.0
      Min-Attack-Cooldown: 1.0