races:
  armat:
    vulnerable-damage-multiplier: 1.5
    sink-gravity-value: 0.42

    # Leather armor set bonus
    damage-inversion:
      lower-bound: 3.0
      upper-bound: 30.0

    # Copper armor set bonus
    mining-bonus:
      upper-bound: 3.0
      step: 0.25

    # Chainmail armor set bonus
    damage-dodge:
      max-chance: 0.5
      parry:
        damage-percent: 0.6
        armor-penalty: 1

    # Iron armor set bonus
    damage-reduction:
      starting-point: 8.0
      damage-multiplier: 0.8

    # Golden armor set bonus
    alchemy:
      effect-duration-multiplier: 1.25

    # Diamond armor set bonus
    absolute-damage:
      amount: 1.0
      min-attack-cooldown: 1.0
  phantom:
    membrane-heal-amount: 1.0