name: WeltenRaces
version: '${version}'
authors: [ JustJabka ]

main: justjabka.WeltenRaces.WeltenRaces
bootstrapper: justjabka.WeltenRaces.WeltenRacesBootstrap
api-version: '1.21.11'
load: POSTWORLD

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true