name: WeltenRaces
version: '${version}'

main: justjabka.WeltenRaces.WeltenRaces
bootstrapper: justjabka.WeltenRaces.WeltenRacesBootstrap
api-version: '1.21.11'
load: POSTWORLD

authors: [ JustJabka ]
