name: JustRacesShowcase
version: '1.0'
authors: [ JustJabka ]

main: justjabka.justraces.showcase.JustRacesShowcase
bootstrapper: justjabka.justraces.showcase.JustRacesShowcaseBootstrap
api-version: '26.2'
load: POSTWORLD

dependencies:
  server:
    JustRaces:
      load: BEFORE
      required: true
      join-classpath: true