name: JustRaces
version: '${version}'
authors: [ JustJabka ]

main: justjabka.JustRaces.JustRaces
bootstrapper: justjabka.JustRaces.JustRacesBootstrap
api-version: '1.21.11'
load: POSTWORLD

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true