name: JustRaces
version: '${version}'
authors: [ JustJabka ]

main: justjabka.justraces.core.JustRaces
bootstrapper: justjabka.justraces.core.JustRacesBootstrap
api-version: '26.2'
load: POSTWORLD

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true